# ----------- STAGE 1: BUILD CLIENT -------------------
FROM node:20-alpine AS build

WORKDIR /app

# Install dependencies
COPY ./client_app/package*.json ./
RUN npm install

# Copy the rest and build
COPY ./client_app/ ./
RUN npm run build

# ----------- STAGE 2: NGINX STATIC SERVER -------------------
FROM nginx:1.28.0-alpine3.21

# Entferne evtl. alte Dateien (optional, bei Custom builds)
#RUN rm -rf /usr/share/nginx/html/*

# Copy the build output from previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Optional: eigene Nginx-Konfiguration
# COPY nginx-config/nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
