services:
  todo-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DB_FILE_PATH=/app/data/db.json
    ports:
      - "8080:8080"
    volumes:
      - todo-data:/app/data

volumes:
  todo-data:
