# Basisimage mit Java 21
FROM amazoncorretto:21-alpine3.21

# Verzeichnis im Container für das JAR
WORKDIR /app

# Das gebaute Fat-JAR in den Container kopieren
COPY build/libs/echo-server-1.0.0-SNAPSHOT-fat.jar app.jar

EXPOSE 8888

# Der Befehl, der beim Containerstart ausgeführt wird
CMD ["java", "-jar", "app.jar"]
